version: "3.8"
name: "TNGMN"

services:
    # client:
    #     extends:
    #         file: ./docker/docker-compose.client.yaml
    #         service: client
    #     networks:
    #         - tngmn

    api:
        extends:
            file: ./docker/docker-compose.api.yaml
            service: api
        build:
            context: ./
            dockerfile: ./apps/api/Dockerfile
        networks:
            - tngmn

    product:
        extends:
            file: ./docker/docker-compose.product.yaml
            service: product
        build:
            context: ./
            dockerfile: ./apps/product/Dockerfile
        networks:
            - tngmn

    user:
        extends:
            file: ./docker/docker-compose.user.yaml
            service: user
        build:
            context: ./
            dockerfile: ./apps/user/Dockerfile
        networks:
            - tngmn

    order:
        extends:
            file: ./docker/docker-compose.order.yaml
            service: order
        build:
            context: ./
            dockerfile: ./apps/order/Dockerfile
        networks:
            - tngmn

    exchequer:
        extends:
            file: ./docker/docker-compose.exchequer.yaml
            service: exchequer
        build:
            context: ./
            dockerfile: ./apps/exchequer/Dockerfile
        networks:
            - tngmn
            - tngmn-exchequer

    # providers
    mongo:
        extends:
            file: ./docker/docker-compose.mongo.yaml
            service: mongo
        networks:
            - tngmn

    exchequer-mongo:
        extends:
            file: ./docker/docker-compose.mongo.yaml
            service: exchequer-mongo
        networks:
            - tngmn-exchequer

    nats:
        extends:
            file: ./docker/docker-compose.nats.yaml
            service: nats
        networks:
            - tngmn

    redis:
        extends:
            file: ./docker/docker-compose.redis.yaml
            service: redis
        networks:
            - tngmn

    redis-commander:
        extends:
            file: ./docker/docker-compose.redis.yaml
            service: redis-commander
        depends_on:
            - redis
        networks:
            - tngmn

networks:
    tngmn:
        driver: bridge
    tngmn-exchequer:
        driver: bridge

volumes:
    tngmndata:
    tngmnradis:
    tngmndataexchequer:
