version: "3.8"
name: "TNGMN"

services:
    # client:
    #     extends:
    #         file: ./docker/docker-compose.client.yaml
    #         service: client
    #     networks:
    #         - tngmn

    api:
        extends:
            file: ./docker/docker-compose.api.yaml
            service: api
        build:
            context: ./
            dockerfile: ./apps/api/Dockerfile
        networks:
            - tngmn

    product:
        # extends:
        #     file: ./docker/docker-compose.product.yaml
        #     service: product
        container_name: product
        restart: always
        build:
            context: ./
            dockerfile: ./apps/product/Dockerfile
        volumes:
            - /usr/app/node_modules
            - ./dist/apps/product:/opt/app/dist
            - /opt/app/node_modules
        env_file:
            - ./envs/.product.env
            - ./envs/.mongo.env
        command: npm run start:prod
        depends_on:
            - nats
            - mongo
        networks:
            - tngmn

    user:
        # extends:
        #     file: ./docker/docker-compose.user.yaml
        #     service: user
        container_name: user
        restart: always
        build:
            context: ./
            dockerfile: ./apps/user/Dockerfile
        volumes:
        - /usr/app/node_modules
            - ./dist/apps/user:/opt/app/dist
            - /opt/app/node_modules
        env_file:
            - ./envs/.user.env
            - ./envs/.mongo.env
        command: npm run start:prod
        depends_on:
            - mongo
            - nats
        networks:
            - tngmn

    mongo:
        extends:
            file: ./docker/docker-compose.mongo.yaml
            service: mongo
        networks:
            - tngmn

    nats:
        extends:
            file: ./docker/docker-compose.nats.yaml
            service: nats
        networks:
            - tngmn

    redis:
        extends:
            file: ./docker/docker-compose.redis.yaml
            service: redis
        networks:
            - tngmn

    redis-commander:
        extends:
            file: ./docker/docker-compose.redis.yaml
            service: redis-commander
        depends_on:
            - redis
        networks:
            - tngmn

networks:
    tngmn:
        driver: bridge

volumes:
    tngmndata:
    tngmnradis:
