version: "3.8"

services:
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - tngmndata:/data/db
    ports:
      # listing outside : listing inside
      - '27017:27017'
    networks:
      - tngmn

  mongo-prod:
    image: mongo
    container_name: mongo
    restart: always
    volumes:
      - tngmndata:/data/db
    expose:
      - '27017'
    networks:
      - tngmn

  exchequer-mongo:
    image: mongo
    container_name: exchequer-mongo
    restart: always
    volumes:
      - tngmndataexchequer:/data/db
    ports:
      # listing outside : listing inside
      - '27018:27017'
    networks:
      - tngmn-exchequer

  exchequer-mongo-prod:
    image: mongo
    container_name: exchequer-mongo
    restart: always
    # environment:
    #   - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
    #   - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - tngmndataexchequer:/data/db
    expose:
      - '27017'
    networks:
      - tngmn-exchequer

networks:
  tngmn:
    driver: bridge
  tngmn-exchequer:
    driver: bridge

volumes:
  tngmndata:
  tngmndataexchequer:
