version: "3.8"

services:
  exchequer:
    container_name: exchequer
    restart: always
    build:
      context: ./
      dockerfile: ../apps/exchequer/Dockerfile
    volumes:
      - /opt/app/node_modules
      - ../dist/apps/exchequer:/opt/app/dist
    env_file:
      - ../envs/.mongo.env
      - ../envs/.nats.env
      - ../envs/.redis.env
      - ../envs/.jwt.env
      - ../envs/.exchequer.env
    command: npm run start:prod
    depends_on:
      - nats
      - exchequer-mongo
      - redis
    networks:
      - tngmn
      - tngmn-exchequer

  exchequer-prod:
    container_name: exchequer-prod
    restart: always
    build:
      context: ./
      dockerfile: ../apps/exchequer/Dockerfile
    volumes:
      - /opt/app/node_modules
    env_file:
      - ../envs/.mongo.env
      - ../envs/.nats.env
      - ../envs/.redis.env
      - ../envs/.jwt.env
      - ../envs/.exchequer.env
    command: npm run start:prod
    depends_on:
      - nats
      - redis
      - exchequer-mongo
    networks:
      - tngmn
      - tngmn-exchequer

networks:
  tngmn:
    driver: bridge
  tngmn-exchequer:
    driver: bridge
