FROM node:16-alpine

ARG NODE_ENV=development
ENV NODE_ENV=${NODE_ENV}

WORKDIR /opt/app

ADD package*.json ./
ADD schema.gql ./schema.gql

RUN npm i -g rimraf
RUN npm i

COPY . .

RUN npm run start:dev admin


